name: "Development"

on:
  workflow_dispatch:
  push:
    branches:
      - workflows

jobs:
  terraform:
    name: "Terraform"
    environment: development
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: ./.github/workflows/shared.terraform.yml
        with:
          terraform_dir: terraform/environments/dev



