name: "Terraform"

on:
  pull_request:
  push:
    branches:
      - master


jobs:
  telegram-bot:
    name: "Telegram bot"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ECR_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.ECR_AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        working-directory: telegram-bot
        run: yarn install --frozen-lockfile

      - name: Terraform init
        working-directory: terraform
        run: terraform init

      - name: Build
        working-directory: telegram-bot
        run: yarn build

      - name: Archive
        working-directory: telegram-bot
        run: |
          yarn install --production
          mv node_modules ./dist/
          zip -r dist.zip ./dist

      - name: Upload to S3
        run: |
          BUCKET=$(terraform -chdir=terraform output -raw  s3_lambda_bucket)
          BUCKET_KEY=$(terraform -chdir=terraform output -raw  s3_lambda_bucket_key)
          aws s3 cp ./telegram-bot/dist.zip s3://$BUCKET/$BUCKET_KEY

      - name: Update function
        run: |
          BUCKET=$(terraform -chdir=terraform output -raw  s3_lambda_bucket)
          BUCKET_KEY=$(terraform -chdir=terraform output -raw  s3_lambda_bucket_key)
          NAME=$(terraform -chdir=terraform output -raw  lambda_name)
          aws lambda update-function-code --function-name $NAME --s3-bucket $BUCKET_KEY --s3-key $BUCKET_KEY
          aws lambda publish-version --function-name $NAME
          

  recorder-service:
    name: "Recorder service"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ECR_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.ECR_AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-3

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Build, tag, and push image to Amazon ECR
        run: |
          ECR_URL=$(terraform -chdir=terraform output -raw  ecr_repository_url)
          docker build -t $ECR_URL:$GITHUB_RUN_ID -t $ECR_URL:latest ./sunset-recorder
          docker push $ECR_URL:$GITHUB_RUN_ID
          docker push $ECR_URL:latest



  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    needs:
      - telegram-bot
      - recorder-service

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          # terraform_version: 0.13.0:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Format
        working-directory: terraform
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        working-directory: terraform
        id: init
        run: terraform init

      - name: Terraform Validate
        working-directory: terraform
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        working-directory: terraform
        id: plan
        if: github.event_name == 'pull_request'
        run: terraform plan -no-color -input=false

      - name: Terraform Apply
        working-directory: terraform
#        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: terraform apply -auto-approve -input=false
