name: "Terraform"

on:
  push:
    paths:
      - sunset-recorder/**
    branches:
      - master

jobs:
  docker:
    name: "Build and deploy"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          # terraform_version: 0.13.0:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        working-directory: terraform
        id: init
        run: terraform init

      - name: Terraform Apply
        working-directory: terraform
        run: |
          
          repository_url=$(terraform output ecr_repository_url)
        
