name: "Terraform"

on:
  push:
    branches:
      - master

jobs:
  docker:
    name: "Build and deploy"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ECR_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.ECR_AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-3

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          # terraform_version: 0.13.0:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Build, tag, and push image to Amazon ECR
        run: |
          ECR_URL=$(terraform -chdir=terraform output ecr_repository_url)
          docker build -t $ECR_URL:${{ github.run_id }} -t $ECR_URL:latest ./sunset-recorder
          docker push $ECR_URL:${{ github.run_id }}
          docker push $ECR_URL:latest
        
