name: "Telegram bot"

on:
  push:
    paths:
      - telegram-bot/**
    branches:
      - master
      - feat/telegram-bot

jobs:
  telegram-bot:
    name: "Build and deploy"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ECR_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.ECR_AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        working-directory: telegram-bot
        run: yarn install --frozen-lockfile

      - name: Build
        working-directory: telegram-bot
        run: yarn build

      - name: Archive
        working-directory: telegram-bot
        run: |
          yarn install --production
          mv node_modules ./dist/
          zip dist.zip ./dist/**/*

      - name: Deploy
        run: |
          BUCKET=$(terraform -chdir=terraform output -raw  s3_lambda_bucket)
          BUCKET_KEY=$(terraform -chdir=terraform output -raw  s3_lambda_bucket_key)
          s3 cp ./telegram-bot/dist.zip s3://$BUCKET/$BUCKET_KEY
